-- Clientes --
CREATE OR REPLACE
    TRIGGER upperCaseCliente
    BEFORE INSERT OR UPDATE
    ON CLIENTE
    FOR EACH ROW
BEGIN
    :NEW.NOMBRE := UPPER(:NEW.NOMBRE);
    :NEW.APELLIDO_PAT := UPPER(:NEW.APELLIDO_PAT);
    :NEW.APELLIDO_MAT := UPPER(:NEW.APELLIDO_MAT);
    :NEW.DOMICILIO := UPPER(:NEW.DOMICILIO);
END;
/

--Productos--
CREATE OR REPLACE
    TRIGGER upperCaseProducto
    BEFORE INSERT OR UPDATE
    ON PRODUCTO
    FOR EACH ROW
BEGIN
    :NEW.DESCRIPCION := UPPER(:NEW.DESCRIPCION);
END;




