version: '3.9'
services:
  java:
    image: amazoncorretto:19
    links:
      - dataBase
  dataBase:
    image:   container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "4859:1521"
      - "5501:5500"
    environment:
      - ORACLE_PWD=admin
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./data:/opt/oracle/oradata
      - ./databaseScripts/setup:/docker-entrypoint-initdb.d/setup
      - ./databaseScripts/startup:/docker-entrypoint-initdb.d/startup
      - ./sqlScripts:/home/oracle/sqlScripts