ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER dev IDENTIFIED BY dev;
ALTER USER dev DEFAULT TABLESPACE USERS;
ALTER USER dev TEMPORARY TABLESPACE TEMP;
ALTER USER dev QUOTA UNLIMITED ON USERS;
ALTER USER dev QUOTA UNLIMITED ON SYSTEM;
GRANT DBA TO dev;